### ISSUE TITLE
<a name="more"> appears to stop markdownification when feed parsing

### ISSUE THREAD

**Issue by glennklockwood** [hpc-social/blog#7]
Blogger uses `<a name="more"></a>` to separate the part of blog posts that should be shown "above the fold" of the landing page. When I try to run [my blog's RSS](https://github.com/glennklockwood/hpc-social-blog/blob/main/_data/authors.yml) through the blog syndicator though, everything past the `<a name="more">` is no longer converted into markdown and is spit out as escaped HTML.

I tried to visually inspect the RSS feed coming out of blogger and its contents _look_ the same above and below this `<a name="more">` divider, so I think something is going wrong upstream of [generate_posts.py](https://github.com/hpc-social/blog/blob/main/scripts/generate_posts.py) (like feedparser?).  Any ideas?  I couldn't find any obvious causes.

**Comment by vsoch** [comment]
Let me do a quick manual debug to see what's going on - back in a bit!

**Comment by vsoch** [comment]
Looks like we will also want some cleanup of the markdown name - blogger produces an interesting path!

```
blog/_posts/glennklockwood/2022-11-24-tag:blogger.com,1999:blog-4307061427721284246.post-2068110509046297403.md
```

**Comment by vsoch** [comment]
okay does this reproduce? E.g., looks ok, but then a lot of html block?

![image](https://user-images.githubusercontent.com/814322/204438021-1a1a612b-2bf2-4265-8dc1-de5c2edb913d.png)

**Comment by vsoch** [comment]
I'm going to also do a nice little refactor to quickly show the author tag 
![image](https://user-images.githubusercontent.com/814322/204439469-4c0615d2-2de7-47fd-ae68-971834d681f0.png)

**Comment by vsoch** [comment]
don't worry working on your bug now!

**Comment by vsoch** [comment]
okay got that fixed - new bug! Blogger (it looks like) prevents you from linking an external image url:

![image](https://user-images.githubusercontent.com/814322/204440790-99ead964-baa8-45d1-94f0-31822e3a00ef.png)

Need to think about a way around this.

**Comment by vsoch** [comment]
This looks like a known (intentional) issue that Google knows about https://support.google.com/blogger/thread/133238986/image-url-from-blogger-googleusercontent-com-is-not-accepted-by-other-websites-if-i-want-to-insert-m?hl=en. I think for now I'm going to try to filter out these images, and perhaps with a later update we can do an efficient way to get and store them. I don't want to start with that because it will take up space very quickly.

**Comment by vsoch** [comment]
okay I've pushed a fix to get you on the map! It includes (for the time being) removing these images that we aren't allowed to embed. If you want to discuss different parsing  strategy please open an issue! The PR also added the nice tags, and better handled the markdown file name and subsequent permalink URL.

**Comment by glennklockwood** [comment]
Thanks for getting this fixed so quickly!  Doesn't seem like many people use Blogger anymore so I appreciate you getting this to work.

It looks like some residual Python crept into the rendered output of <https://hpc.social/blog/2022/sc-22-recap/>:

<img width="664" alt="Screenshot 2022-11-28 at 21 33 02" src="https://user-images.githubusercontent.com/4400938/204447131-504c4c5b-96fa-4dca-9a6a-c431257c900d.png">

Not the end of the world; just fyi.

**Comment by vsoch** [comment]
haha no you are spot on, I caught that too (just pushed a fix!) I needed to stringify the soup instead of returning renderedContent.

**Comment by vsoch** [comment]
should be less terrible now :laughing: 
![image](https://user-images.githubusercontent.com/814322/204448400-f77f5b8f-0bd3-49e1-8db4-946f48f68b7b.png)
